# -*- coding: utf-8 -*-
"""understanding_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i0QclFV3fCpizqnMcBtBVS1fTGrohCLT
"""

import pandas as pd

df = pd.read_csv('train.csv')

"""# 1. How big is the data?"""

df.shape

"""# 2. How does the data look like?"""

df.sample(5)

"""# 3. What is the data type of cols?"""

df.info()

"""# 4. Are there any missing values?"""

df.isnull().sum()

"""# 5. How does the data look mathematically?"""

df.describe()

"""# 6. Are there duplicate values?"""

df.duplicated().sum() #drop duplicated function

"""# 7. How is the correlation between cols?"""

df.corr()

df.corr()['Survived']