# -*- coding: utf-8 -*-
"""univariate_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qMSGQWj_bpOX_QRrhiNu9NYKzH62Q7hV
"""

import pandas as pd
import seaborn as sns

df = pd.read_csv('train.csv')

df.head()

"""# 1. Categorical Data

## a. Countplot
"""

sns.countplot(df['Embarked'])
#df['Survived'].value_counts().plot(kind='bar')

"""## b. PieChart"""

df['Sex'].value_counts().plot(kind='pie',autopct='%.2f')

"""<div style="border-top:black 2px solid"></div>

# 2. Numerical Data

## a. Histogram
"""

import matplotlib.pyplot as plt
plt.hist(df['Age'],bins=5)

"""## b. Distplot"""

sns.distplot(df['Age'])

"""## c. Boxplot"""

sns.boxplot(df['Age'])

df['Age'].min()

df['Age'].max()

df['Age'].mean()

df['Age'].skew()

