# -*- coding: utf-8 -*-
"""bivariate_multivariate_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1osF8RTgV8XPeyacdCbj_bSAiKnx1A-aF
"""

import pandas as pd
import seaborn as sns

tips = sns.load_dataset('tips')

tips.head()

titanic = pd.read_csv('train.csv')

flights = sns.load_dataset('flights')

flights.head()

iris = sns.load_dataset('iris')

iris

"""## 1. Scatterplot (Numerical - Numerical)"""

sns.scatterplot(tips['total_bill'],tips['tip'],hue=df['sex'],style=df['smoker'],size=df['size'])

"""## 2. Bar Plot (Numerical - Categorical)"""

titanic.head()

sns.barplot(titanic['Pclass'],titanic['Age'],hue=titanic['Sex'])

"""## 3. Box Plot (Numerical - Categorical)"""

sns.boxplot(titanic['Sex'],titanic['Age'],hue=titanic['Survived'])

"""## 4. Distplot (Numerical - Categorical)"""

sns.distplot(titanic[titanic['Survived']==0]['Age'],hist=False)
sns.distplot(titanic[titanic['Survived']==1]['Age'],hist=False)

"""## 5. HeatMap (Categorical - Categorical)"""

titanic.head(3)

sns.heatmap(pd.crosstab(titanic['Pclass'],titanic['Survived']))

(titanic.groupby('Embarked').mean()['Survived']*100)

"""## 6. ClusterMap (Categorical - Categorical)"""

sns.clustermap(pd.crosstab(titanic['Parch'],titanic['Survived']))

"""## 7. Pairplot"""

iris.head()

sns.pairplot(iris,hue='species')

"""## 8. Lineplot (Numerical - Numerical)"""

flights.head()

new = flights.groupby('year').sum().reset_index()

sns.lineplot(new['year'],new['passengers'])

flights

sns.clustermap(flights.pivot_table(values='passengers',index='month',columns='year'))

